# Generated by Django 2.2 on 2020-12-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField()),
                ('original_release', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleGamePositives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('consolegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameversions.ConsoleGame')),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleGameNegatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('consolegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameversions.ConsoleGame')),
            ],
        ),
        migrations.AddField(
            model_name='consolegame',
            name='collection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='gameversions.Game'),
        ),
        migrations.AddField(
            model_name='consolegame',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameversions.Console'),
        ),
        migrations.AddField(
            model_name='consolegame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameversions.Game'),
        ),
        migrations.AddField(
            model_name='console',
            name='games',
            field=models.ManyToManyField(through='gameversions.ConsoleGame', to='gameversions.Game'),
        ),
    ]
