# Generated by Django 2.2 on 2020-12-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameversions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolegame',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='gameversions.Game'),
        ),
    ]
