# Generated by Django 2.2 on 2020-12-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameversions', '0002_auto_20201209_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolegame',
            name='cover',
            field=models.ImageField(default='images/games/cover/Default_No_Cover.png', upload_to='images/games/cover'),
        ),
    ]
