# Generated by Django 2.2 on 2020-12-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameversions', '0003_consolegame_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='images/games/cover/Default_No_Cover.png', upload_to='images/games/cover'),
        ),
    ]
