# Generated by Django 2.2 on 2020-12-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameversions', '0007_auto_20201209_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolegamenegatives',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consolegamepositives',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
